---
- name: Install Docker and Docker Compose on Amazon Linux 2
  hosts: ec2-instance
  become: true

  tasks:
    - name: Update package cache
      yum:
        name: "*"
        state: latest
      become: true

    - name: Install Docker dependencies
      yum:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - amazon-linux-extras
        - docker

    - name: Enable Docker Amazon Linux Extras
      become: true
      command: amazon-linux-extras enable docker -y

    - name: Install Docker
      become: true
      yum:
        name: docker
        state: present

    - name: Start Docker service
      become: true
      service:
        name: docker
        state: started

    - name: Add user to docker group
      become: true
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install Docker Compose
      become: true
      command: >
        curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_machine }} -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Make Docker Compose executable
      become: true
      file:
        path: /usr/local/bin/docker-compose
        mode: +x
