name: CDK Deploy

on:
  push:
    branches: ["develop"]
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and publish docker image to Docker Hub.
        run: |
          export TAG="$GITHUB_SHA"
          sudo docker build -t mahdou/node-app-image:${TAG} .
          sudo docker push mahdou/node-example-1:${TAG}

  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            CONTAINER_NAME="app-node"
            sudo docker stop $CONTAINER_NAME || true
            echo "Hello from the remote server!"
            sudo docker run --rm -d --name $CONTAINER_NAME -p 80:80 mahdou/node-example-1
          '
