name: CDK Deploy

on:
  push:
    branches: ["develop"]
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}
          COMMIT_SHA: $GITHUB_SHA

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            CONTAINER_NAME="app-node-'${COMMIT_SHA}'"
            sudo docker stop $CONTAINER_NAME || true
            echo "Hello from the remote server!"
            sudo docker run --rm -d --name $CONTAINER_NAME -p 80:80 mahdou/node-example-1
          '
